function criarLockscreen(){let e=document.createElement("div");e.id="lockscreen",e.classList.add("lockscreen"),e.style.willChange="opacity, transform",e.style.backfaceVisibility="hidden",e.style.transform="translateZ(0)";let t=document.createElement("div");t.classList.add("lock-content"),t.style.willChange="transform, opacity";let a=document.createElement("div");a.classList.add("click-text"),a.innerHTML="[ click to unlock ]",a.style.willChange="opacity, transform";let i=document.createElement("style");i.textContent=`
      @keyframes pulse {
          0% { transform: scale(1); }
          50% { transform: scale(1.05); }
          100% { transform: scale(1); }
      }
      .click-text {
          animation: pulse 1.5s infinite ease-in-out;
      }
  `,document.head.appendChild(i),t.appendChild(a),e.appendChild(t),document.body.insertBefore(e,document.body.firstChild);let l=document.getElementById("container");l&&(l.style.opacity="0",l.style.visibility="hidden",l.style.transition="opacity 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000), visibility 0s linear 0.8s",l.style.willChange="opacity");let s=document.querySelectorAll(".elemento-para-animar");s.forEach(e=>{e.style.opacity="0",e.style.transform="translateY(20px)",e.style.willChange="opacity, transform",e.classList.remove("animate-fade-in")});let n=!1;e.addEventListener("click",()=>{n||(n=!0,a.style.animation="none",e.style.transition="opacity 500ms cubic-bezier(0.165, 0.84, 0.44, 1), transform 500ms cubic-bezier(0.165, 0.84, 0.44, 1)",e.style.opacity="0",e.style.transform="scale(1.1) translateZ(0)",setTimeout(()=>{l&&(l.style.visibility="visible",l.style.opacity="1",l.style.transition="opacity 1.2s cubic-bezier(0.4, 0, 0.2, 1)"),new Audio("/img/music.mp3").play().catch(e=>console.log("Audio play failed:",e)),setTimeout(()=>{animarElementosSequencialmente()},200),setTimeout(()=>{e.remove()},800)},500))})}function animarElementosSequencialmente(){let e=document.querySelectorAll(".elemento-para-animar");e.forEach(e=>{let t=Array.from(e.classList).find(e=>e.startsWith("delay-")),a=0;if(t){let i=parseInt(t.replace("delay-",""),10);a=100*i}else e.dataset.delay&&(a=parseInt(e.dataset.delay,10));setTimeout(()=>{e.style.transition="opacity 500ms cubic-bezier(0.4, 0, 0.2, 1), transform 500ms cubic-bezier(0.4, 0, 0.2, 1)",e.style.opacity="1",e.style.transform="translateY(0)",setTimeout(()=>{e.style.willChange="auto"},500)},a)})}document.addEventListener("DOMContentLoaded",()=>{criarLockscreen();let e=document.querySelectorAll(".elemento-para-animar");e.length>0&&e.forEach(e=>{if("IntersectionObserver"in window){let t=new IntersectionObserver(e=>{e.forEach(e=>{e.isIntersecting&&(e.target.style.willChange="opacity, transform",t.unobserve(e.target))})});t.observe(e)}})});
